### ISSUE TITLE
Create API design

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#21]

**Comment by StephenTanksley** [comment]
I'd be able to tackle API design.

**Comment by StephenTanksley** [comment]
API Design Discussion:

These fields should be included in the token because it will permit conditional rendering. both fields can be true simultaneously as situations change. 

```
volunteer: true || false; 
in_need: true || false;
```

As a user, I want to be able to toggle my status as a volunteer or if I’m in_need as the situation changes.
   
We’ll need to use unique identifiers from users to create a unique “request”.  Possible contenders: UID, email. Jan suggests email (which needs to be unique already). 

The cons to the use of email is that email can be traced across the web if someone were to gain access as opposed to a UID which is more generic and abstract.
