### ISSUE TITLE
Figure out to do geolocation queries in Firebase using the GeoPoint data type

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#28]

**Comment by SerTalithaT** [comment]
Hi! I can take this 😄

**Comment by SerTalithaT** [comment]
Like all data types within firebase, GeoPoints can be accessed via a get on the collection or set a listener: https://firebase.google.com/docs/firestore/query-data/get-data. 
For the JS version, it's properties are latitude and longitude and are accessed accordingly. It has one method, isEqual for comparing against other GeoPoints. And any lat & long data can be transformed into a GeoPoint. https://firebase.google.com/docs/reference/node/firebase.firestore.GeoPoint

**Comment by SerTalithaT** [comment]
I did look into Google Maps APIs and services and there is no existing functionality for finding if a geo marker is within a given radius. 
They do have a call that allows for this, [containsLocation](https://developers.google.com/maps/documentation/javascript/examples/poly-containsLocation), but it only works for polygon shapes, not circles. 

But there is a computeDistanceBetween() function that should do the trick https://developers.google.com/maps/documentation/javascript/geometry?hl=en#Distance. However, it does take a [LatLng](https://developers.google.com/maps/documentation/javascript/reference/coordinates)  object rather than a GeoPoint. Conversion between the two types is about as simple as you'd imagine: https://stackoverflow.com/questions/53799346/how-to-convert-geopoint-in-firestore-to-latlng (of course we could also easily make our own helper function that does the equivalent of the official Maps computeDistanceBetween using only the GeoPoint class)

Regardless, with a bit of optimization, you could make a solid algorithm to quickly determine the possible markers within a given radius.

**Comment by thebitguru** [comment]
Thank you for your help!  We will have to identify all the requests within a given distance from the location of the volunteer.  I am thinking that this will likely end up as a query on the Firestore server.  Sounds like Firestore doesn't support a "query within x miles (or equivalent)" out of the box?

**Comment by thebitguru** [comment]
FYI, @MrSimsek helped with this today in https://github.com/CV19Assist/app/pull/36 so we are all set.  Thank you for your help with this, @SerTalithaT and @MrSimsek!
